#pragma once

#include "Types.h"

// Project descriptor (the data contract). The generated header emits a const
// instance and the shared engine reads it. Invariant: a generated scene struct
// is determined only by ID/type; coordinates, size, style, and profile live in
// this descriptor, kept independent from the Arduino-side usage code (§8.2).
//
// Evolution rule (SPEC §10.1): these descriptor structs are positional
// aggregates initialized positionally by the generated header. New fields are
// APPENDED with a default member initializer set to the legacy/neutral value,
// so a header generated by an older tool (which omits the new field) still
// compiles and behaves the same (the omitted field takes its default). Reordering
// or removing a field is a breaking change to the data contract: bump the
// contract and regenerate the header from the project file.
namespace lgfxsb
{

  // Static definition of a part (the profile-independent portion). All parts of
  // all scenes are laid out in a single array, sliced by SceneDesc.
  struct PartDesc
  {
    const char *id = nullptr;
    PartType type = PartType::Rect;
    int16_t assetIndex = -1;      // referenced asset for Image (-1 = none)
  };

  // Per-profile layout of a part (§8.9.6). Each profile holds complete,
  // independent values. Access as layouts[profileIndex * partCount + partIndex].
  struct PartLayout
  {
    int16_t x = 0, y = 0;     // scene coordinates (Text: the anchor point)
    int16_t w = 0, h = 0;     // rectangle size for Rect/Image (unused for Text)
    int16_t x2 = 0, y2 = 0;   // Line end point
    int16_t r = 0;            // corner radius for Rect / radius for Circle
    uint8_t datum = 0;        // Text datum (Datum)
    float size = 1.0f;        // Text size multiplier (equivalent to setTextSize)
    uint32_t color = 0;       // 0xRRGGBB (Rect fill / Text color)
    bool fill = true;         // Rect: true = fill, false = outline
    bool visible = true;
    const void *font = nullptr; // Text preset font: &lgfx::v1::fonts::X, or null = default.
                          // void* keeps this header framework-agnostic (the Renderer
                          // casts to const lgfx::v1::IFont*).
    const char *text = nullptr; // Text design/preview string for THIS profile (§8.7).
                          // Used when no dynamic value is supplied, so each profile
                          // can show its own fixed-label text. null = empty.
  };

  struct SceneDesc
  {
    SceneId id = 0;
    const char *name = nullptr;
    uint16_t partStart = 0;   // start index into parts[]
    uint16_t partCount = 0;

    // Transparent (overlay) scene (§8.16): a dialog-style screen drawn ON TOP of
    // whatever is already on the panel. The background fill is skipped and, in a
    // buffered build, the tile is pushed with Project::transparentColor masked
    // out. Appended per the evolution rule above: a header from an older tool
    // omits it and every scene stays opaque.
    bool transparent = false;
  };

  // Profile definition (§8.9). Auto-detection is based on screen size only.
  struct ProfileDesc
  {
    int16_t w = 0, h = 0;
    uint8_t rotation = 0;
  };

  // Image asset: RGB565 pixels (row-major), referenced by PartDesc::assetIndex
  // (§8.4, Header/PROGMEM + RAW RGB565).
  struct AssetDesc
  {
    const uint16_t *data = nullptr;
    int16_t w = 0, h = 0;
  };

  struct Project
  {
    const ProfileDesc *profiles = nullptr;
    uint8_t profileCount = 0;

    const SceneDesc *scenes = nullptr;
    uint16_t sceneCount = 0;

    const PartDesc *parts = nullptr;    // all parts of all scenes (referenced by range from SceneDesc)
    uint16_t partCount = 0;

    const PartLayout *layouts = nullptr; // [profileCount][partCount]

    uint32_t background = 0;             // full-screen fill color 0xRRGGBB (§7.4)

    // Appended after background so older generated headers (which omit these)
    // take the defaults below (see the evolution rule at the top of this file).
    const AssetDesc *assets = nullptr;   // image assets (RGB565); referenced by PartDesc::assetIndex
    uint16_t assetCount = 0;

    // Color-key for transparent scenes (§8.16), 0xRRGGBB. Only meaningful when a
    // scene has SceneDesc::transparent set; a project without one omits it, so
    // the default stands. The default is LovyanGFX's TFT_TRANSPARENT (RGB565
    // 0x0120) expressed as RGB888 == LGFXVirtualCanvas's own default.
    uint32_t transparentColor = 0x002400;
  };

} // namespace lgfxsb
