"""Generate fonts_table.h for the font-introspection harness (SPEC §8.7.2, 1b).

Mirrors tools/gen-fonts.mjs version resolution: the LovyanGFX version is taken
from the tools/fontgen/sketch.yaml pin (the single source of truth), and the
matching copy is resolved under ~/.arduino15/internal/<Name>_<version>_<hash>.
We parse the `extern const lgfx::<Type> <Name>;` declarations in the `fonts`
namespace and emit a C++ table of {name, &fonts::<Name>} so the harness can
introspect every preset font uniformly through its IFont base.

Fails loudly if the pinned version is not downloaded (build tools/fontgen once).
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
INTERNAL = Path.home() / ".arduino15" / "internal"
FONTGEN_SKETCH = ROOT / "tools" / "fontgen" / "sketch.yaml"


def pinned_version(name="LovyanGFX"):
    """Read the pinned library version from tools/fontgen/sketch.yaml."""
    text = FONTGEN_SKETCH.read_text()
    m = re.search(rf"^\s*-\s*{re.escape(name)}\s*\(([^)]+)\)", text, re.M)
    if not m:
        raise RuntimeError(f"{FONTGEN_SKETCH} must pin {name} (e.g. '- {name} (1.2.21)')")
    return m.group(1).strip()


def resolve_header(name, version):
    """Resolve lgfx_fonts.hpp for the EXACT pinned version under internal."""
    if not INTERNAL.exists():
        raise RuntimeError(f"{INTERNAL} does not exist — build tools/fontgen first.")
    prefix = f"{name}_{version}_"
    dirs = sorted(d for d in INTERNAL.iterdir() if d.name.startswith(prefix))
    if not dirs:
        raise RuntimeError(
            f"{name} {version} not found under {INTERNAL}.\n"
            f"Pinned in tools/fontgen/sketch.yaml but not yet downloaded — build it once:\n"
            f"  arduino-cli compile --profile host tools/fontgen"
        )
    if len(dirs) > 1:
        print(f"! {name} {version}: {len(dirs)} copies, using {dirs[0].name}")
    header = dirs[0] / name / "src" / "lgfx" / "v1" / "lgfx_fonts.hpp"
    if not header.exists():
        raise RuntimeError(f"{header} missing")
    return header


def parse_fonts(header_path):
    """Return [(type, name)] for every extern font in the `fonts` namespace."""
    src = header_path.read_text()
    block = src[src.index("namespace fonts"):]
    return re.findall(r"extern\s+const\s+lgfx::(\w*[Ff]ont)\s+(\w+)\s*;", block)


def generate():
    version = pinned_version("LovyanGFX")
    header = resolve_header("LovyanGFX", version)
    fonts = parse_fonts(header)
    if not fonts:
        raise RuntimeError(f"no fonts parsed from {header}")

    entries = "\n".join(f'  {{ "{n}", &lgfx::v1::fonts::{n} }},' for _t, n in fonts)
    out = (
        "// GENERATED by gen.py from lgfx_fonts.hpp — do not edit by hand.\n"
        f"// Source: LovyanGFX {version} (representative catalog, SPEC §8.7.2).\n"
        "#pragma once\n"
        "#include <LovyanGFX.hpp>\n\n"
        "struct FontEntry { const char* name; const lgfx::v1::IFont* font; };\n\n"
        "static const FontEntry kFonts[] = {\n"
        f"{entries}\n"
        "};\n"
        "static const size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);\n"
    )
    (HERE / "fonts_table.h").write_text(out)
    print(f"wrote fonts_table.h: {len(fonts)} fonts (LovyanGFX {version})")
    return [n for _t, n in fonts], version


if __name__ == "__main__":
    generate()
