#pragma once

// Generated by LGFXScreenBuilder (formatVersion 1). Do not edit by hand.
// Include <LovyanGFX.hpp> (or M5GFX) and <LGFXScreenBuilder.h> before this header.

namespace CompatV1 {

enum class Profile : uint8_t { Auto = 0, Core, Stick, CoreRot };

namespace Scene {
  struct Boot {
    static constexpr lgfxsb::SceneId id = 0;
    const char* msg = nullptr;  // design: Booting...
  };
  struct Showcase {
    static constexpr lgfxsb::SceneId id = 1;
    const char* heading = nullptr;  // design: Showcase
    const char* note = nullptr;  // design: core
  };
}

namespace detail {

static const lgfxsb::PartDesc kParts[] = {
  {"bg", lgfxsb::PartType::Rect, -1},  // 0 Boot.bg
  {"msg", lgfxsb::PartType::Text, -1},  // 1 Boot.msg
  {"bg", lgfxsb::PartType::Rect, -1},  // 2 Showcase.bg
  {"frame", lgfxsb::PartType::Rect, -1},  // 3 Showcase.frame
  {"sep", lgfxsb::PartType::Line, -1},  // 4 Showcase.sep
  {"dotF", lgfxsb::PartType::Circle, -1},  // 5 Showcase.dotF
  {"ring", lgfxsb::PartType::Circle, -1},  // 6 Showcase.ring
  {"heading", lgfxsb::PartType::Text, -1},  // 7 Showcase.heading
  {"note", lgfxsb::PartType::Text, -1},  // 8 Showcase.note
  {"icon", lgfxsb::PartType::Image, 0},  // 9 Showcase.icon
};
static constexpr uint16_t kPartCount = 10;

static const lgfxsb::SceneDesc kScenes[] = {
  {0, "Boot", 0, 2},
  {1, "Showcase", 2, 8},
};

// {x, y, w, h, x2, y2, r, datum, size, color, fill, visible, font, text}
static const lgfxsb::PartLayout kLayouts[] = {
  // ---- Profile: Core 320x240 rot0 ----
  {0, 0, 320, 240, 0, 0, 0, 0, 0.0f, 0x101418, true, true, nullptr, nullptr},  // Boot.bg
  {160, 120, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MidCenter, 2.0f, 0x9ce5ac, true, true, nullptr, "Booting..."},  // Boot.msg
  {0, 0, 320, 240, 0, 0, 0, 0, 0.0f, 0x0b0f12, true, true, nullptr, nullptr},  // Showcase.bg
  {8, 8, 304, 224, 0, 0, 10, 0, 0.0f, 0x2a3a44, false, true, nullptr, nullptr},  // Showcase.frame
  {16, 48, 0, 0, 304, 48, 0, 0, 0.0f, 0x3a4a55, true, true, nullptr, nullptr},  // Showcase.sep
  {60, 160, 0, 0, 0, 0, 24, 0, 0.0f, 0x4caf50, true, true, nullptr, nullptr},  // Showcase.dotF
  {140, 160, 0, 0, 0, 0, 24, 0, 0.0f, 0xffb300, false, true, nullptr, nullptr},  // Showcase.ring
  {160, 28, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopCenter, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::FreeSans12pt7b, "Showcase"},  // Showcase.heading
  {16, 200, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 1.5f, 0x9ce5ac, true, true, nullptr, "core"},  // Showcase.note
  {260, 140, 40, 40, 0, 0, 0, 0, 0.0f, 0, true, true, nullptr, nullptr},  // Showcase.icon
  // ---- Profile: Stick 135x240 rot0 ----
  {0, 0, 135, 240, 0, 0, 0, 0, 0.0f, 0x101418, true, true, nullptr, nullptr},  // Boot.bg
  {67, 120, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MidCenter, 1.5f, 0x9ce5ac, true, true, nullptr, "Boot..."},  // Boot.msg
  {0, 0, 135, 240, 0, 0, 0, 0, 0.0f, 0x0b0f12, true, true, nullptr, nullptr},  // Showcase.bg
  {4, 4, 127, 232, 0, 0, 8, 0, 0.0f, 0x2a3a44, false, true, nullptr, nullptr},  // Showcase.frame
  {8, 40, 0, 0, 127, 40, 0, 0, 0.0f, 0x3a4a55, true, true, nullptr, nullptr},  // Showcase.sep
  {40, 150, 0, 0, 0, 0, 18, 0, 0.0f, 0x4caf50, true, true, nullptr, nullptr},  // Showcase.dotF
  {95, 150, 0, 0, 0, 0, 18, 0, 0.0f, 0xffb300, false, true, nullptr, nullptr},  // Showcase.ring
  {67, 22, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopCenter, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::FreeSans12pt7b, "Show"},  // Showcase.heading
  {8, 210, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 1.5f, 0x9ce5ac, true, true, nullptr, "stick"},  // Showcase.note
  {100, 130, 28, 28, 0, 0, 0, 0, 0.0f, 0, true, true, nullptr, nullptr},  // Showcase.icon
  // ---- Profile: CoreRot 320x240 rot1 ----
  {0, 0, 240, 320, 0, 0, 0, 0, 0.0f, 0x101418, true, true, nullptr, nullptr},  // Boot.bg
  {120, 160, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MidCenter, 2.0f, 0x9ce5ac, true, true, nullptr, "Booting..."},  // Boot.msg
  {0, 0, 240, 320, 0, 0, 0, 0, 0.0f, 0x0b0f12, true, true, nullptr, nullptr},  // Showcase.bg
  {8, 8, 224, 304, 0, 0, 10, 0, 0.0f, 0x2a3a44, false, true, nullptr, nullptr},  // Showcase.frame
  {16, 56, 0, 0, 224, 56, 0, 0, 0.0f, 0x3a4a55, true, true, nullptr, nullptr},  // Showcase.sep
  {60, 200, 0, 0, 0, 0, 22, 0, 0.0f, 0x4caf50, true, true, nullptr, nullptr},  // Showcase.dotF
  {140, 200, 0, 0, 0, 0, 22, 0, 0.0f, 0xffb300, false, true, nullptr, nullptr},  // Showcase.ring
  {120, 32, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopCenter, 1.0f, 0xffffff, true, true, &lgfx::v1::fonts::FreeSans12pt7b, "Showcase"},  // Showcase.heading
  {16, 280, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 1.5f, 0x9ce5ac, true, true, nullptr, "rot1"},  // Showcase.note
  {180, 180, 40, 40, 0, 0, 0, 0, 0.0f, 0, true, true, nullptr, nullptr},  // Showcase.icon
};

static const lgfxsb::ProfileDesc kProfiles[] = {
  {320, 240, 0},
  {135, 240, 0},
  {320, 240, 1},
};

struct ProfileInfo {
  const char* name;
  uint8_t index;
  int16_t w, h;
  uint8_t rotation;
};

struct SceneInfo {
  const char* name;
  lgfxsb::SceneId id;
  uint16_t index;
};

static constexpr ProfileInfo kProfileInfo[] = {
  {"Core", 0, 320, 240, 0},
  {"Stick", 1, 135, 240, 0},
  {"CoreRot", 2, 320, 240, 1},
};
static constexpr uint8_t kProfileInfoCount = 3;

static constexpr SceneInfo kSceneInfo[] = {
  {"Boot", Scene::Boot::id, 0},
  {"Showcase", Scene::Showcase::id, 1},
};
static constexpr uint16_t kSceneInfoCount = 2;

static const uint16_t kAsset_logo1[] = { 0xf800 };  // 1x1
static const lgfxsb::AssetDesc kAssets[] = {
  { kAsset_logo1, 1, 1 },
};

} // namespace detail

static const lgfxsb::Project project = {
  detail::kProfiles, 3,
  detail::kScenes, 2,
  detail::kParts, detail::kPartCount,
  detail::kLayouts,
  /*background*/ 0x000000,
  detail::kAssets, 1,
};

#if defined(LGFXVIRTUALCANVAS_H)
using Canvas = LGFXVirtualCanvas;
#else
using Canvas = lgfx::LGFXBase;
#endif

class Screen : public lgfxsb::RendererT<Canvas> {
  using Base = lgfxsb::RendererT<Canvas>;
  void (*_ov_Boot)(Canvas&, const Scene::Boot&) = nullptr;
  static void _ovt_Boot(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::Boot&)>(fnp))(g, *static_cast<const Scene::Boot*>(s)); }
  void (*_ov_Showcase)(Canvas&, const Scene::Showcase&) = nullptr;
  static void _ovt_Showcase(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::Showcase&)>(fnp))(g, *static_cast<const Scene::Showcase*>(s)); }
 public:
  explicit Screen(lgfx::LGFX_Device& gfx) : Base(gfx, project) {}
  void setProfile(Profile p) { _profile = static_cast<uint8_t>(p); }
  void show(lgfxsb::SceneId id) { renderScene(id, nullptr, 0); }
  void show(const Scene::Boot& s) {
    lgfxsb::Value v[2];
    if (s.msg) v[1] = lgfxsb::Value::text(s.msg);
    renderScene(Scene::Boot::id, v, 2, _ov_Boot ? &_ovt_Boot : nullptr, &s, &_ov_Boot);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::Boot&)) { _ov_Boot = fn; }
  void show(const Scene::Showcase& s) {
    lgfxsb::Value v[8];
    if (s.heading) v[5] = lgfxsb::Value::text(s.heading);
    if (s.note) v[6] = lgfxsb::Value::text(s.note);
    renderScene(Scene::Showcase::id, v, 8, _ov_Showcase ? &_ovt_Showcase : nullptr, &s, &_ov_Showcase);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::Showcase&)) { _ov_Showcase = fn; }
};

} // namespace CompatV1
