#pragma once

// Generated by LGFXScreenBuilder (formatVersion 1). Do not edit by hand.
// Include <LovyanGFX.hpp> (or M5GFX) and <LGFXScreenBuilder.h> before this header.

namespace MyScreen {

enum class Profile : uint8_t { Auto = 0, Core, Stick, Cardputer };

namespace Scene {
  struct Boot {
    static constexpr lgfxsb::SceneId id = 0;
    const char* boot = nullptr;  // design: Booting...
  };
  struct Main {
    static constexpr lgfxsb::SceneId id = 1;
    const char* title = nullptr;  // design: Main
    const char* battery = nullptr;  // design: 82%
    const char* temp = nullptr;  // design: 24.5C
  };
  struct Settings {
    static constexpr lgfxsb::SceneId id = 2;
    const char* ttl = nullptr;  // design: Settings
    const char* row1 = nullptr;  // design: Wi-Fi
  };
  // Transparent scene: drawn ON TOP of whatever is on the panel (no background
  // fill). Show the screen underneath again to dismiss it.
  struct Dialog {
    static constexpr lgfxsb::SceneId id = 3;
    const char* msg = nullptr;  // design: Delete?
    const char* hint = nullptr;  // design: A:OK B:Cancel
  };
}

namespace detail {

static const lgfxsb::PartDesc kParts[] = {
  {"logo", lgfxsb::PartType::Rect, -1},  // 0 Boot.logo
  {"boot", lgfxsb::PartType::Text, -1},  // 1 Boot.boot
  {"headerBand", lgfxsb::PartType::Rect, -1},  // 2 Main.headerBand
  {"title", lgfxsb::PartType::Text, -1},  // 3 Main.title
  {"battery", lgfxsb::PartType::Text, -1},  // 4 Main.battery
  {"temp", lgfxsb::PartType::Text, -1},  // 5 Main.temp
  {"panel", lgfxsb::PartType::Rect, -1},  // 6 Main.panel
  {"header", lgfxsb::PartType::Rect, -1},  // 7 Settings.header
  {"ttl", lgfxsb::PartType::Text, -1},  // 8 Settings.ttl
  {"row1", lgfxsb::PartType::Text, -1},  // 9 Settings.row1
  {"shadow", lgfxsb::PartType::Rect, -1},  // 10 Dialog.shadow
  {"box", lgfxsb::PartType::Rect, -1},  // 11 Dialog.box
  {"frame", lgfxsb::PartType::Rect, -1},  // 12 Dialog.frame
  {"msg", lgfxsb::PartType::Text, -1},  // 13 Dialog.msg
  {"hint", lgfxsb::PartType::Text, -1},  // 14 Dialog.hint
};
static constexpr uint16_t kPartCount = 15;

static const lgfxsb::SceneDesc kScenes[] = {
  {0, "Boot", 0, 2},
  {1, "Main", 2, 5},
  {2, "Settings", 7, 3},
  {3, "Dialog", 10, 5, true},
};

// {x, y, w, h, x2, y2, r, datum, size, color, fill, visible, font, text}
static const lgfxsb::PartLayout kLayouts[] = {
  // ---- Profile: Core 320x240 rot0 ----
  {110, 80, 100, 60, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr, nullptr},  // Boot.logo
  {160, 160, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MidCenter, 2.0f, 0x9ce5ac, true, true, nullptr, "Booting..."},  // Boot.boot
  {0, 0, 320, 40, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr, nullptr},  // Main.headerBand
  {12, 10, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 2.0f, 0xffffff, true, true, nullptr, "Main"},  // Main.title
  {310, 12, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopRight, 1.5f, 0x9ce5ac, true, true, nullptr, "82%"},  // Main.battery
  {18, 70, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 4.0f, 0xffffff, true, true, nullptr, "24.5C"},  // Main.temp
  {18, 150, 284, 54, 0, 0, 0, 0, 0.0f, 0x172126, true, true, nullptr, nullptr},  // Main.panel
  {0, 0, 320, 40, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr, nullptr},  // Settings.header
  {12, 10, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 2.0f, 0xffffff, true, true, nullptr, "Settings"},  // Settings.ttl
  {18, 60, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 2.0f, 0xffffff, true, true, nullptr, "Wi-Fi"},  // Settings.row1
  {66, 76, 200, 100, 0, 0, 10, 0, 0.0f, 0x000000, true, true, nullptr, nullptr},  // Dialog.shadow
  {60, 70, 200, 100, 0, 0, 10, 0, 0.0f, 0x1e2a30, true, true, nullptr, nullptr},  // Dialog.box
  {60, 70, 200, 100, 0, 0, 10, 0, 0.0f, 0x9ce5ac, false, true, nullptr, nullptr},  // Dialog.frame
  {160, 105, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MidCenter, 2.0f, 0xffffff, true, true, nullptr, "Delete?"},  // Dialog.msg
  {160, 145, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MidCenter, 1.5f, 0x9ce5ac, true, true, nullptr, "A:OK  B:Cancel"},  // Dialog.hint
  // ---- Profile: Stick 135x240 rot0 ----
  {30, 80, 75, 50, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr, nullptr},  // Boot.logo
  {69, 148, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MidCenter, 1.5f, 0x9ce5ac, true, true, nullptr, "Boot..."},  // Boot.boot
  {0, 0, 135, 30, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr, nullptr},  // Main.headerBand
  {8, 7, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 1.5f, 0xffffff, true, true, nullptr, "Main"},  // Main.title
  {8, 180, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 1.5f, 0x9ce5ac, true, true, nullptr, "82%"},  // Main.battery
  {10, 60, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 3.5f, 0xffffff, true, true, nullptr, "24.5"},  // Main.temp
  {10, 110, 115, 60, 0, 0, 0, 0, 0.0f, 0x172126, true, true, nullptr, nullptr},  // Main.panel
  {0, 0, 135, 30, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr, nullptr},  // Settings.header
  {8, 7, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 1.5f, 0xffffff, true, true, nullptr, "Settings"},  // Settings.ttl
  {10, 40, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 1.5f, 0xffffff, true, true, nullptr, "Wi-Fi"},  // Settings.row1
  {14, 84, 115, 80, 0, 0, 8, 0, 0.0f, 0x000000, true, true, nullptr, nullptr},  // Dialog.shadow
  {10, 80, 115, 80, 0, 0, 8, 0, 0.0f, 0x1e2a30, true, true, nullptr, nullptr},  // Dialog.box
  {10, 80, 115, 80, 0, 0, 8, 0, 0.0f, 0x9ce5ac, false, true, nullptr, nullptr},  // Dialog.frame
  {67, 105, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MidCenter, 1.5f, 0xffffff, true, true, nullptr, "Delete?"},  // Dialog.msg
  {67, 140, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MidCenter, 1.0f, 0x9ce5ac, true, true, nullptr, "A:OK B:No"},  // Dialog.hint
  // ---- Profile: Cardputer 240x135 rot0 ----
  {80, 30, 80, 40, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr, nullptr},  // Boot.logo
  {120, 88, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MidCenter, 1.5f, 0x9ce5ac, true, true, nullptr, "Booting..."},  // Boot.boot
  {0, 0, 240, 26, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr, nullptr},  // Main.headerBand
  {8, 5, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 1.5f, 0xffffff, true, true, nullptr, "Main"},  // Main.title
  {232, 6, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopRight, 1.25f, 0x9ce5ac, true, true, nullptr, "82%"},  // Main.battery
  {12, 40, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 3.0f, 0xffffff, true, true, nullptr, "24.5C"},  // Main.temp
  {12, 86, 216, 40, 0, 0, 0, 0, 0.0f, 0x172126, true, false, nullptr, nullptr},  // Main.panel
  {0, 0, 240, 26, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr, nullptr},  // Settings.header
  {8, 5, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 1.5f, 0xffffff, true, true, nullptr, "Settings"},  // Settings.ttl
  {12, 36, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TopLeft, 1.5f, 0xffffff, true, true, nullptr, "Wi-Fi"},  // Settings.row1
  {44, 34, 160, 75, 0, 0, 8, 0, 0.0f, 0x000000, true, true, nullptr, nullptr},  // Dialog.shadow
  {40, 30, 160, 75, 0, 0, 8, 0, 0.0f, 0x1e2a30, true, true, nullptr, nullptr},  // Dialog.box
  {40, 30, 160, 75, 0, 0, 8, 0, 0.0f, 0x9ce5ac, false, true, nullptr, nullptr},  // Dialog.frame
  {120, 55, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MidCenter, 1.5f, 0xffffff, true, true, nullptr, "Delete?"},  // Dialog.msg
  {120, 88, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MidCenter, 1.0f, 0x9ce5ac, true, true, nullptr, "A:OK  B:Cancel"},  // Dialog.hint
};

static const lgfxsb::ProfileDesc kProfiles[] = {
  {320, 240, 0},
  {135, 240, 0},
  {240, 135, 0},
};

struct ProfileInfo {
  const char* name;
  uint8_t index;
  int16_t w, h;
  uint8_t rotation;
};

struct SceneInfo {
  const char* name;
  lgfxsb::SceneId id;
  uint16_t index;
};

static constexpr ProfileInfo kProfileInfo[] = {
  {"Core", 0, 320, 240, 0},
  {"Stick", 1, 135, 240, 0},
  {"Cardputer", 2, 240, 135, 0},
};
static constexpr uint8_t kProfileInfoCount = 3;

static constexpr SceneInfo kSceneInfo[] = {
  {"Boot", Scene::Boot::id, 0},
  {"Main", Scene::Main::id, 1},
  {"Settings", Scene::Settings::id, 2},
  {"Dialog", Scene::Dialog::id, 3},
};
static constexpr uint16_t kSceneInfoCount = 4;


} // namespace detail

static const lgfxsb::Project project = {
  detail::kProfiles, 3,
  detail::kScenes, 4,
  detail::kParts, detail::kPartCount,
  detail::kLayouts,
  /*background*/ 0x000000,
  nullptr, 0,
  /*transparentColor*/ 0x002400,
};

#if defined(LGFXVIRTUALCANVAS_H)
using Canvas = LGFXVirtualCanvas;
#else
using Canvas = lgfx::LGFXBase;
#endif

class Screen : public lgfxsb::RendererT<Canvas> {
  using Base = lgfxsb::RendererT<Canvas>;
  void (*_ov_Boot)(Canvas&, const Scene::Boot&) = nullptr;
  static void _ovt_Boot(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::Boot&)>(fnp))(g, *static_cast<const Scene::Boot*>(s)); }
  void (*_ov_Main)(Canvas&, const Scene::Main&) = nullptr;
  static void _ovt_Main(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::Main&)>(fnp))(g, *static_cast<const Scene::Main*>(s)); }
  void (*_ov_Settings)(Canvas&, const Scene::Settings&) = nullptr;
  static void _ovt_Settings(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::Settings&)>(fnp))(g, *static_cast<const Scene::Settings*>(s)); }
  void (*_ov_Dialog)(Canvas&, const Scene::Dialog&) = nullptr;
  static void _ovt_Dialog(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::Dialog&)>(fnp))(g, *static_cast<const Scene::Dialog*>(s)); }
 public:
  explicit Screen(lgfx::LGFX_Device& gfx) : Base(gfx, project) {}
  void setProfile(Profile p) { _profile = static_cast<uint8_t>(p); }
  void show(lgfxsb::SceneId id) { renderScene(id, nullptr, 0); }
  void show(const Scene::Boot& s) {
    lgfxsb::Value v[2];
    if (s.boot) v[1] = lgfxsb::Value::text(s.boot);
    renderScene(Scene::Boot::id, v, 2, _ov_Boot ? &_ovt_Boot : nullptr, &s, &_ov_Boot);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::Boot&)) { _ov_Boot = fn; }
  void show(const Scene::Main& s) {
    lgfxsb::Value v[5];
    if (s.title) v[1] = lgfxsb::Value::text(s.title);
    if (s.battery) v[2] = lgfxsb::Value::text(s.battery);
    if (s.temp) v[3] = lgfxsb::Value::text(s.temp);
    renderScene(Scene::Main::id, v, 5, _ov_Main ? &_ovt_Main : nullptr, &s, &_ov_Main);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::Main&)) { _ov_Main = fn; }
  void show(const Scene::Settings& s) {
    lgfxsb::Value v[3];
    if (s.ttl) v[1] = lgfxsb::Value::text(s.ttl);
    if (s.row1) v[2] = lgfxsb::Value::text(s.row1);
    renderScene(Scene::Settings::id, v, 3, _ov_Settings ? &_ovt_Settings : nullptr, &s, &_ov_Settings);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::Settings&)) { _ov_Settings = fn; }
  void show(const Scene::Dialog& s) {
    lgfxsb::Value v[5];
    if (s.msg) v[3] = lgfxsb::Value::text(s.msg);
    if (s.hint) v[4] = lgfxsb::Value::text(s.hint);
    renderScene(Scene::Dialog::id, v, 5, _ov_Dialog ? &_ovt_Dialog : nullptr, &s, &_ov_Dialog);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::Dialog&)) { _ov_Dialog = fn; }
};

} // namespace MyScreen
