"""Font catalog + introspection-harness generator (SPEC §8.7.2).

This is the single source for the preset-font artifacts (it replaced the old
node `tools/gen-fonts.mjs`). The LovyanGFX version is taken from the
tools/fontcatalog/sketch.yaml pin (the single source of truth) and the matching copy
is resolved under ~/.arduino15/internal/<Name>_<version>_<hash>; if the pinned
version is not downloaded it fails loudly (build tools/fontcatalog once) rather than
silently parsing an old copy.

Two outputs, both regenerated by running this file (`python gen.py`):
  - docs/src/font-catalog.js — name-derived classification of every preset font
    (LovyanGFX is the representative single catalog; M5GFX is diff-checked).
  - fonts_table.h — a C++ table {name, &fonts::<Name>, sample} so the harness can
    introspect every font through its IFont base. The test calls generate() for
    this at collection; the host metrics/atlas/flash come from the harness run.
"""
import json
import re
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent       # tests/manual/font_introspect
ROOT = HERE.parents[2]                        # repo root
DOCS_SRC = ROOT / "docs" / "src"
INTERNAL = Path.home() / ".arduino15" / "internal"
FONTCATALOG_SKETCH = ROOT / "tools" / "fontcatalog" / "sketch.yaml"

CATEGORY = {
    "GLCDfont": "bitmap", "BMPfont": "bitmap", "RLEfont": "bitmap", "FixedBMPfont": "bitmap",
    "GFXfont": "gfx", "U8g2font": "u8g2", "BDFfont": "bdf", "VLWfont": "vlw",
}


def pinned_version(name="LovyanGFX"):
    """Read the pinned library version from tools/fontcatalog/sketch.yaml."""
    text = FONTCATALOG_SKETCH.read_text()
    m = re.search(rf"^\s*-\s*{re.escape(name)}\s*\(([^)]+)\)", text, re.M)
    if not m:
        raise RuntimeError(f"{FONTCATALOG_SKETCH} must pin {name} (e.g. '- {name} (1.2.21)')")
    return m.group(1).strip()


def resolve_header(name, version):
    """Resolve lgfx_fonts.hpp for the EXACT pinned version under internal."""
    if not INTERNAL.exists():
        raise RuntimeError(f"{INTERNAL} does not exist — build tools/fontcatalog first.")
    prefix = f"{name}_{version}_"
    dirs = sorted(d for d in INTERNAL.iterdir() if d.name.startswith(prefix))
    if not dirs:
        raise RuntimeError(
            f"{name} {version} not found under {INTERNAL}.\n"
            f"Pinned in tools/fontcatalog/sketch.yaml but not yet downloaded — build it once:\n"
            f"  arduino-cli compile --profile host tools/fontcatalog"
        )
    if len(dirs) > 1:
        print(f"! {name} {version}: {len(dirs)} copies, using {dirs[0].name}")
    header = dirs[0] / name / "src" / "lgfx" / "v1" / "lgfx_fonts.hpp"
    if not header.exists():
        raise RuntimeError(f"{header} missing")
    return header


def ensure_downloaded(version):
    """Ensure the pinned LovyanGFX is under ~/.arduino15/internal.

    On a clean machine (e.g. CI) the pinned libs are only downloaded on the first
    compile of the profile, so internal is empty and resolve_header would fail.
    Building the tools/fontcatalog stub once populates internal with the exact pinned
    LovyanGFX + M5GFX (the documented bootstrap step). No-op once present.
    """
    prefix = f"LovyanGFX_{version}_"
    if INTERNAL.exists() and any(d.name.startswith(prefix) for d in INTERNAL.iterdir()):
        return
    fontcatalog = ROOT / "tools" / "fontcatalog"
    print(f"LovyanGFX {version} not under internal — building {fontcatalog} to download pinned libs...")
    subprocess.run(["arduino-cli", "compile", "--profile", "host", str(fontcatalog)], check=True)


def parse_fonts(header_path):
    """Return [(type, name)] for every extern font in the `fonts` namespace."""
    src = header_path.read_text()
    block = src[src.index("namespace fonts"):]
    return re.findall(r"extern\s+const\s+lgfx::(\w*[Ff]ont)\s+(\w+)\s*;", block)


def script_of(name):
    """Language/script of a font from its name: latin, or one of the CJK locales
    ja / cn / tw / ko (more useful as a filter than a single 'cjk', §8.7.2)."""
    if re.match(r"efontCN", name):
        return "cn"
    if re.match(r"efontTW", name):
        return "tw"
    if re.match(r"efontKR", name):
        return "ko"
    if re.search(r"efontJA|lgfxJapan|Mincho|Gothic|Japan|Kanji", name):
        return "ja"
    return "latin"


def classify(type_sym, name):
    """Classify a font from its type symbol + name into filterable attributes."""
    category = CATEGORY.get(type_sym, "other")
    bold = bool(re.search(r"Bold|_bi?$", name))
    italic = bool(re.search(r"Oblique|Italic|_b?i$", name))
    script = script_of(name)
    family, size, unit = name, None, None

    if m := re.match(r"^(.*?)(\d+)pt7b$", name):            # GFX: FreeSansBold12pt7b
        family = re.sub(r"(Bold|Oblique|Italic)+$", "", m.group(1))
        size, unit = int(m.group(2)), "pt"
    elif m := re.match(r"^efont([A-Z]{2})?_(\d+)(_(b|i|bi))?$", name):  # efontCN_16_bi
        family = "efont" + (m.group(1) or "")
        size, unit = int(m.group(2)), "px"
    elif m := re.match(r"^(.*?)_(\d+)$", name):             # Orbitron_Light_24 / lgfxJapanGothic_8
        family = re.sub(r"_+$", "", m.group(1))
        size, unit = int(m.group(2)), "px"
    elif category != "bitmap" and (m := re.match(r"^([A-Za-z]+?)(\d+)$", name)):  # DejaVu40
        family, size, unit = m.group(1), int(m.group(2)), "px"

    if category == "bitmap":                               # classics: keep name as family
        family, size, unit = name, None, None

    return {"name": name, "type": type_sym, "category": category, "family": family,
            "bold": bold, "italic": italic, "size": size, "unit": unit, "script": script}


def sample_for(cls):
    """Preview sample string for a font. Latin shows width contrast (W wide vs
    ili narrow, so a fixed-pitch font visibly aligns); CJK uses the self-naming
    script word (so the language is obvious, every glyph high-frequency) plus
    "ABC123" since CJK fonts also carry ASCII and the latin glyphs are otherwise
    invisible in the preview (SPEC §8.7.2). Digit-only fonts are detected at
    render time and overridden to all ten digits in the harness, not here."""
    s = cls["script"]
    if s == "latin":
        return "Wax Lily 12"
    if s == "cn":
        return "简体中文 ABC123"   # Simplified Chinese
    if s == "tw":
        return "繁體中文 ABC123"   # Traditional Chinese
    if s == "ko":
        return "한국어 ABC123"     # Korean
    return "日本語 ABC123"          # ja: lgfxJapan*, efontJA


def classified(version):
    return [classify(t, n) for t, n in parse_fonts(resolve_header("LovyanGFX", version))]


def write_catalog():
    """Write docs/src/font-catalog.js (name-derived classification, browser-read)."""
    version = pinned_version("LovyanGFX")
    ensure_downloaded(version)
    cats = classified(version)
    print(f"LovyanGFX {version}: {len(cats)} fonts (representative catalog)")

    # Diff guard: if a future bump makes M5GFX's set diverge, flag it. Best-effort.
    m5note = "M5GFX assumed identical (not checked)"
    try:
        m5v = pinned_version("M5GFX")
        m5 = {n for _t, n in parse_fonts(resolve_header("M5GFX", m5v))}
        only_l, only_m = {c["name"] for c in cats} - m5, m5 - {c["name"] for c in cats}
        if only_l or only_m:
            print(f"! font set DIVERGES from M5GFX {m5v}: LovyanGFX-only {len(only_l)}, M5GFX-only {len(only_m)}")
            m5note = f"DIVERGES from M5GFX {m5v} (LovyanGFX-only {len(only_l)}, M5GFX-only {len(only_m)}) — using LovyanGFX"
        else:
            print(f"M5GFX {m5v}: identical font set (diff guard OK)")
            m5note = f"identical to M5GFX {m5v} (diff-checked)"
    except RuntimeError as e:
        print(f"! M5GFX diff check skipped: {str(e).splitlines()[0]}")

    banner = (
        "// GENERATED by tests/manual/font_introspect/gen.py from lgfx_fonts.hpp. Do not edit by hand.\n"
        f"// Source: LovyanGFX {version} (representative single catalog; {m5note}).\n"
        "// Name-derived classification only (SPEC §8.7.2); host metrics/coverage/size/preview\n"
        "// are added by the same harness into font-metrics.json + font-atlas.png.\n"
    )
    body = (
        f"export const FONT_CATALOG = {json.dumps(cats, ensure_ascii=False, separators=(',', ':'))};\n\n"
        "// Single representative catalog. At the pinned versions LovyanGFX and M5GFX\n"
        "// share the same font set, so every target library uses this one catalog.\n"
        "export const catalogFor = (_lib) => FONT_CATALOG;\n"
    )
    (DOCS_SRC / "font-catalog.js").write_text(banner + body)
    print("wrote docs/src/font-catalog.js")


def _data_symbols(cpp_text):
    """Map each non-GFX font name to the data symbols it references.

    The classic (GLCD/BMP/RLE) and U8g2/efont font objects in lgfx_fonts.cpp
    point to separately-named data arrays, e.g. `const U8g2font lgfxJapanGothic_16
    = { lgfx_font_japan_gothic_16 };`. We capture the identifier (non-numeric)
    initializer tokens so their linked sizes can be summed. GFX fonts are absent
    here (defined in included .h files) — they use name-prefixed data symbols
    (<Name>Bitmaps / <Name>Glyphs) instead.
    """
    out = {}
    for m in re.finditer(r"const\s+\w*[Ff]ont\s+(\w+)\s*=\s*\{([^}]*)\}", cpp_text):
        ids = [re.sub(r"\([^)]*\)", "", t).strip() for t in m.group(2).split(",")]
        out[m.group(1)] = [t for t in ids if re.fullmatch(r"[A-Za-z_]\w*", t)]
    return out


def font_flash_sizes(elf_path, names, version):
    """Exact per-font flash bytes from a single linked ELF (no per-font builds).

    Each preset font's flash cost = its font object + its data arrays. nm gives
    every symbol's size; we attribute by demangled leaf name (GFX: <Name> +
    <Name>Bitmaps/Glyphs; others: <Name> + the data symbols parsed from the .cpp).
    At the pinned version only `font0_info` (3 bytes) is shared, so these are
    effectively the marginal link cost of adopting each font. Returns {name: bytes}
    or {} if nm / the ELF / the source are unavailable (best-effort enrichment).
    """
    try:
        cpp = resolve_header("LovyanGFX", version).with_name("lgfx_fonts.cpp").read_text()
        nm = subprocess.run(
            ["nm", "-C", "--print-size", "--radix=d", str(elf_path)],
            capture_output=True, text=True, check=True,
        ).stdout
    except (FileNotFoundError, subprocess.CalledProcessError, RuntimeError) as e:
        print(f"! per-font flash size skipped: {e}")
        return {}

    leaf = {}
    for line in nm.splitlines():
        parts = line.split(maxsplit=3)
        if len(parts) == 4 and parts[1].isdigit():
            key = parts[3].split("::")[-1]
            leaf[key] = leaf.get(key, 0) + int(parts[1])

    dmap = _data_symbols(cpp)

    def syms(n):
        return dmap[n] if n in dmap else [n + "Bitmaps", n + "Glyphs"]

    return {n: leaf.get(n, 0) + sum(leaf.get(d, 0) for d in syms(n)) for n in names}


def generate():
    """Write fonts_table.h for the harness; return (font names, version)."""
    version = pinned_version("LovyanGFX")
    ensure_downloaded(version)
    fonts = parse_fonts(resolve_header("LovyanGFX", version))
    if not fonts:
        raise RuntimeError("no fonts parsed")

    rows = []
    for t, n in fonts:
        sample = sample_for(classify(t, n)).replace('"', '\\"')
        rows.append(f'  {{ "{n}", &lgfx::v1::fonts::{n}, "{sample}" }},')
    out = (
        "// GENERATED by gen.py from lgfx_fonts.hpp — do not edit by hand.\n"
        f"// Source: LovyanGFX {version} (representative catalog, SPEC §8.7.2).\n"
        "#pragma once\n"
        "#include <LovyanGFX.hpp>\n\n"
        "struct FontEntry { const char* name; const lgfx::v1::IFont* font; const char* sample; };\n\n"
        "static const FontEntry kFonts[] = {\n"
        f"{chr(10).join(rows)}\n"
        "};\n"
        "static const size_t kFontCount = sizeof(kFonts) / sizeof(kFonts[0]);\n"
    )
    (HERE / "fonts_table.h").write_text(out)
    print(f"wrote fonts_table.h: {len(fonts)} fonts (LovyanGFX {version})")
    return [n for _t, n in fonts], version


if __name__ == "__main__":
    write_catalog()
    generate()
