#pragma once

// Generated by LGFXScreenBuilder (formatVersion 1). Do not edit by hand.
// Include <LovyanGFX.hpp> (or M5GFX) and <LGFXScreenBuilder.h> before this header.

namespace MyScreen {

enum class Profile : uint8_t { Auto = 0, Core, Stick, Cardputer };

namespace Scene {
  struct Boot {
    static constexpr lgfxsb::SceneId id = 0;
    const char* boot = "Booting...";
  };
  struct Main {
    static constexpr lgfxsb::SceneId id = 1;
    const char* title = "Main";
    const char* battery = "82%";
    const char* temp = "24.5C";
  };
  struct Settings {
    static constexpr lgfxsb::SceneId id = 2;
    const char* ttl = "Settings";
    const char* row1 = "Wi-Fi";
  };
}

namespace detail {

static const lgfxsb::PartDesc kParts[] = {
  {"logo", lgfxsb::PartType::Rect, nullptr, -1},  // 0 Boot.logo
  {"boot", lgfxsb::PartType::Text, "Booting...", -1},  // 1 Boot.boot
  {"headerBand", lgfxsb::PartType::Rect, nullptr, -1},  // 2 Main.headerBand
  {"title", lgfxsb::PartType::Text, "Main", -1},  // 3 Main.title
  {"battery", lgfxsb::PartType::Text, "82%", -1},  // 4 Main.battery
  {"temp", lgfxsb::PartType::Text, "24.5C", -1},  // 5 Main.temp
  {"panel", lgfxsb::PartType::Rect, nullptr, -1},  // 6 Main.panel
  {"header", lgfxsb::PartType::Rect, nullptr, -1},  // 7 Settings.header
  {"ttl", lgfxsb::PartType::Text, "Settings", -1},  // 8 Settings.ttl
  {"row1", lgfxsb::PartType::Text, "Wi-Fi", -1},  // 9 Settings.row1
};
static constexpr uint16_t kPartCount = 10;

static const lgfxsb::SceneDesc kScenes[] = {
  {0, "Boot", 0, 2},
  {1, "Main", 2, 5},
  {2, "Settings", 7, 3},
};

// {x, y, w, h, x2, y2, r, datum, size, color, fill, visible, font}
static const lgfxsb::PartLayout kLayouts[] = {
  // ---- Profile: Core 320x240 rot0 ----
  {110, 80, 100, 60, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // Boot.logo
  {160, 160, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 2.0f, 0x9ce5ac, true, true, nullptr},  // Boot.boot
  {0, 0, 320, 40, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // Main.headerBand
  {12, 10, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TL, 2.0f, 0xffffff, true, true, nullptr},  // Main.title
  {310, 12, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TR, 1.5f, 0x9ce5ac, true, true, nullptr},  // Main.battery
  {18, 70, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TL, 4.0f, 0xffffff, true, true, nullptr},  // Main.temp
  {18, 150, 284, 54, 0, 0, 0, 0, 0.0f, 0x172126, true, true, nullptr},  // Main.panel
  {0, 0, 320, 40, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // Settings.header
  {12, 10, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TL, 2.0f, 0xffffff, true, true, nullptr},  // Settings.ttl
  {18, 60, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TL, 2.0f, 0xffffff, true, true, nullptr},  // Settings.row1
  // ---- Profile: Stick 135x240 rot0 ----
  {30, 80, 75, 50, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // Boot.logo
  {69, 148, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.5f, 0x9ce5ac, true, true, nullptr},  // Boot.boot
  {0, 0, 135, 30, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // Main.headerBand
  {8, 7, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TL, 1.5f, 0xffffff, true, true, nullptr},  // Main.title
  {8, 180, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TL, 1.5f, 0x9ce5ac, true, true, nullptr},  // Main.battery
  {10, 60, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TL, 3.5f, 0xffffff, true, true, nullptr},  // Main.temp
  {10, 110, 115, 60, 0, 0, 0, 0, 0.0f, 0x172126, true, true, nullptr},  // Main.panel
  {0, 0, 135, 30, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // Settings.header
  {8, 7, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TL, 1.5f, 0xffffff, true, true, nullptr},  // Settings.ttl
  {10, 40, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TL, 1.5f, 0xffffff, true, true, nullptr},  // Settings.row1
  // ---- Profile: Cardputer 240x135 rot0 ----
  {80, 30, 80, 40, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // Boot.logo
  {120, 88, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::MC, 1.5f, 0x9ce5ac, true, true, nullptr},  // Boot.boot
  {0, 0, 240, 26, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // Main.headerBand
  {8, 5, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TL, 1.5f, 0xffffff, true, true, nullptr},  // Main.title
  {232, 6, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TR, 1.25f, 0x9ce5ac, true, true, nullptr},  // Main.battery
  {12, 40, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TL, 3.0f, 0xffffff, true, true, nullptr},  // Main.temp
  {12, 86, 216, 40, 0, 0, 0, 0, 0.0f, 0x172126, true, false, nullptr},  // Main.panel
  {0, 0, 240, 26, 0, 0, 0, 0, 0.0f, 0x1e2a30, true, true, nullptr},  // Settings.header
  {8, 5, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TL, 1.5f, 0xffffff, true, true, nullptr},  // Settings.ttl
  {12, 36, 0, 0, 0, 0, 0, (uint8_t)lgfxsb::Datum::TL, 1.5f, 0xffffff, true, true, nullptr},  // Settings.row1
};

static const lgfxsb::ProfileDesc kProfiles[] = {
  {320, 240, 0},
  {135, 240, 0},
  {240, 135, 0},
};

struct ProfileInfo {
  const char* name;
  uint8_t index;
  int16_t w, h;
  uint8_t rotation;
};

struct SceneInfo {
  const char* name;
  lgfxsb::SceneId id;
  uint16_t index;
};

static constexpr ProfileInfo kProfileInfo[] = {
  {"Core", 0, 320, 240, 0},
  {"Stick", 1, 135, 240, 0},
  {"Cardputer", 2, 240, 135, 0},
};
static constexpr uint8_t kProfileInfoCount = 3;

static constexpr SceneInfo kSceneInfo[] = {
  {"Boot", Scene::Boot::id, 0},
  {"Main", Scene::Main::id, 1},
  {"Settings", Scene::Settings::id, 2},
};
static constexpr uint16_t kSceneInfoCount = 3;


} // namespace detail

static const lgfxsb::Project project = {
  detail::kProfiles, 3,
  detail::kScenes, 3,
  detail::kParts, detail::kPartCount,
  detail::kLayouts,
  /*background*/ 0x000000,
  nullptr, 0,
};

#if defined(LGFXVIRTUALCANVAS_H)
using Canvas = LGFXVirtualCanvas;
#else
using Canvas = lgfx::LGFXBase;
#endif

class Screen : public lgfxsb::RendererT<Canvas> {
  using Base = lgfxsb::RendererT<Canvas>;
  void (*_ov_Boot)(Canvas&, const Scene::Boot&) = nullptr;
  static void _ovt_Boot(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::Boot&)>(fnp))(g, *static_cast<const Scene::Boot*>(s)); }
  void (*_ov_Main)(Canvas&, const Scene::Main&) = nullptr;
  static void _ovt_Main(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::Main&)>(fnp))(g, *static_cast<const Scene::Main*>(s)); }
  void (*_ov_Settings)(Canvas&, const Scene::Settings&) = nullptr;
  static void _ovt_Settings(Canvas& g, const void* s, const void* fnp) { (*static_cast<void (*const*)(Canvas&, const Scene::Settings&)>(fnp))(g, *static_cast<const Scene::Settings*>(s)); }
 public:
  explicit Screen(lgfx::LGFX_Device& gfx) : Base(gfx, project) {}
  void setProfile(Profile p) { _profile = static_cast<uint8_t>(p); }
  void show(lgfxsb::SceneId id) { renderScene(id, nullptr, 0); }
  void show(const Scene::Boot& s) {
    lgfxsb::Value v[2];
    v[1] = lgfxsb::Value::text(s.boot);
    renderScene(Scene::Boot::id, v, 2, _ov_Boot ? &_ovt_Boot : nullptr, &s, &_ov_Boot);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::Boot&)) { _ov_Boot = fn; }
  void show(const Scene::Main& s) {
    lgfxsb::Value v[5];
    v[1] = lgfxsb::Value::text(s.title);
    v[2] = lgfxsb::Value::text(s.battery);
    v[3] = lgfxsb::Value::text(s.temp);
    renderScene(Scene::Main::id, v, 5, _ov_Main ? &_ovt_Main : nullptr, &s, &_ov_Main);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::Main&)) { _ov_Main = fn; }
  void show(const Scene::Settings& s) {
    lgfxsb::Value v[3];
    v[1] = lgfxsb::Value::text(s.ttl);
    v[2] = lgfxsb::Value::text(s.row1);
    renderScene(Scene::Settings::id, v, 3, _ov_Settings ? &_ovt_Settings : nullptr, &s, &_ov_Settings);
  }
  void setOverlay(void (*fn)(Canvas&, const Scene::Settings&)) { _ov_Settings = fn; }
};

} // namespace MyScreen
