#include <LovyanGFX.hpp>
#include <LGFX_AUTODETECT.hpp>
#include <LGFXScreenBuilder.h>
#include "MyScreen.h" // generated by gen.mjs (authoring tool codegen)

#include <stdio.h>
#include <sys/stat.h>

using namespace MyScreen;

static LGFX lcd;
static Screen screen(lcd);

static bool savePng(LovyanGFX &src, const char *path)
{
  size_t len = 0;
  void *png = src.createPng(&len, 0, 0, src.width(), src.height());
  if (!png || len == 0)
  {
    return false;
  }
  FILE *fp = fopen(path, "wb");
  bool ok = false;
  if (fp)
  {
    ok = (fwrite(png, 1, len, fp) == len);
    fclose(fp);
  }
  free(png);
  return ok;
}

void setup()
{
  Serial.begin(115200);
  Serial.println("TEST start codegen_roundtrip");

  mkdir("output", 0755);
  lcd.init();
  screen.begin();
  Serial.printf("PANEL %dx%d\n", (int)lcd.width(), (int)lcd.height());

  screen.show(Scene::Boot{});
  Serial.printf("BOOT saved=%d\n", savePng(lcd, "output/boot.png"));

  Scene::Main main;
  main.title = "Main";
  main.battery = "82%";
  main.temp = "24.5C";
  screen.show(main);
  Serial.printf("MAIN saved=%d\n", savePng(lcd, "output/main.png"));

  screen.show(Scene::Settings{});
  Serial.printf("SETTINGS saved=%d\n", savePng(lcd, "output/settings.png"));

  Serial.println("TEST done");
}

void loop()
{
  delay(1000);
}
