// Generated by LGFXScreenBuilder. Example sketch (M5Unified).
// Tours every screen: press button A for the next one.
// A transparent scene lands on top of the screen shown before it; the next
// screen in the tour repaints the whole panel again.
#include <M5Unified.h>
// Tiled double-buffering (less flicker). Install the LGFXVirtualCanvas library;
// without it this falls back to direct drawing. Delete this block to draw directly.
// This project has a transparent scene, so buffered drawing wants
// LGFXVirtualCanvas 1.4.0 or newer (older versions draw it opaque).
#if __has_include(<LGFXVirtualCanvas.h>)
#include <LGFXVirtualCanvas.h>
#else
#warning "LGFXVirtualCanvas not found - drawing directly. Install it for flicker-free buffering."
#endif
#include <LGFXScreenBuilder.h>
#include "MyScreen.h"

using namespace MyScreen;

static Screen screen(M5.Display);

static uint16_t sceneIdx = 0;
static const uint16_t kSceneCount = detail::kSceneInfoCount;

void setup() {
  M5.begin();
  screen.begin();  // Profile::Auto resolves by screen size

  screen.show(sceneIdx);  // first screen, design/preview state

  // To draw live data, fill a scene struct and show it instead of show(id):
  //   Scene::Boot s;  s.boot = "...";  screen.show(s);
}

void loop() {
  M5.update();
  if (M5.BtnA.wasPressed()) {  // press button A for the next screen
    sceneIdx = (sceneIdx + 1) % kSceneCount;
    screen.show(sceneIdx);
  }
  delay(1);
}
